# Generated by Django 2.2 on 2020-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='valid_till',
            field=models.DateTimeField(),
        ),
    ]
